name: Build

on:
  push:
    branches:
      - convert
      - data
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout DCS Docs
        uses: actions/checkout@v2
        with:
          ref: data
          path: data

      - name: Run Build
        run: make build