name: Build

on:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Convert
        uses: actions/checkout@v2
        with:
          ref: convert

      - name: Checkout DCS Docs
        uses: actions/checkout@v2
        with:
          ref: data
          path: data

      - name: Run Build
        run: make build